spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: 2.0

loans:
  message: "Welcome to eazyBank - qa"
  contactInfo:
    name: "Sandhya"
    email: "s@gmail.com"
  onCallSupport: 89099999
